### ISSUE TITLE
crontab example problem

### ISSUE THREAD

**Issue by brunoberte** [sebastianfeldmann/phpbu-documentation#2]
The command is outdated, should be using --configuration parameter
http://phpbu.de/manual/current/en/configuration.html#configuration.schedule

```
# this requires phpbu to be in the cron users path
10     3    *    *    * phpbu --configuration=/var/www/my-backup/phpbu.xml

# alternatively you can specify the full path
#10     3    *    *    * /home/user/bin/phpbu.phar --configuration=/var/www/my-backup/phpbu.xml
```

**Comment by sebastianfeldmann** [comment]
Hi,
thanks for reporting this. I just fixed the crontab example
http://phpbu.de/manual/current/en/configuration.html#configuration.schedule
